# Generated by Django 3.2.8 on 2022-07-28 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lider', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'isla',
                'verbose_name_plural': 'isla',
                'db_table': 'isla',
            },
        ),
        migrations.CreateModel(
            name='UserIsla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isla', to='islas.isla')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendedor isla',
                'verbose_name_plural': 'vendedores islas',
                'db_table': 'isla_user',
            },
        ),
        migrations.CreateModel(
            name='SalesIsla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ci', models.IntegerField(blank=True, null=True)),
                ('min', models.IntegerField()),
                ('icc', models.IntegerField()),
                ('nip', models.IntegerField(blank=True, null=True)),
                ('operadora', models.CharField(blank=True, choices=[('claro', 'Claro'), ('cnt', 'Cnt'), ('movistar', 'Movistar')], max_length=20, null=True)),
                ('nota', models.TextField(blank=True, max_length=255, null=True)),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip', to='lider.product')),
                ('isla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleisla', to='islas.isla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venta islas',
                'verbose_name_plural': 'vetas islas',
                'db_table': 'sales_isla',
            },
        ),
    ]
