# Generated by Django 3.2.8 on 2022-07-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesisla',
            options={'verbose_name': 'venta islas', 'verbose_name_plural': 'ventas islas'},
        ),
        migrations.AlterField(
            model_name='isla',
            name='address',
            field=models.CharField(max_length=255, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='isla',
            name='description',
            field=models.TextField(max_length=255, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='isla',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
