# Generated by Django 3.2.8 on 2022-07-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user_token'),
        ('islas', '0002_auto_20220728_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isla',
            options={'verbose_name': 'isla', 'verbose_name_plural': 'islas'},
        ),
        migrations.AddField(
            model_name='isla',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.distribuidora'),
            preserve_default=False,
        ),
    ]
