# Generated by Django 3.2.8 on 2022-08-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user_token'),
        ('islas', '0003_auto_20220728_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isla',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuidora', to='usuario.distribuidora'),
        ),
    ]
