# Generated by Django 3.2.8 on 2022-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips_sale', models.IntegerField(default=0)),
                ('chips_portability', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips_sale', models.IntegerField(default=0)),
                ('chips_portability', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_current',
            },
        ),
    ]
