# Generated by Django 3.2.8 on 2022-04-15 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagen de producto')),
                ('name', models.CharField(max_length=100, verbose_name='nombre del producto')),
                ('description', models.CharField(max_length=255, verbose_name='descripcion del producto')),
                ('price_in', models.FloatField(verbose_name='precio para el vendedor')),
                ('price_out', models.FloatField(verbose_name='precio para el cliente')),
                ('seller_commission', models.FloatField(verbose_name='comision del vendedor')),
                ('pay_commission', models.BooleanField(verbose_name='Pagar comision')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.category')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.distribuidora')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20)),
                ('subtotal', models.FloatField()),
                ('commission_paid', models.FloatField(default=0.0)),
                ('commission_receivable', models.FloatField(default=0.0)),
                ('discount', models.FloatField()),
                ('total', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('commission_paid', models.FloatField(default=0.0)),
                ('commission_receivable', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendedor.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.report')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
    ]
