# Generated by Django 3.2.8 on 2022-05-09 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20)),
                ('subtotal', models.FloatField()),
                ('commission_paid', models.FloatField(default=0.0)),
                ('commission_receivable', models.FloatField(default=0.0)),
                ('discount', models.FloatField()),
                ('total', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('commission_paid', models.FloatField(default=0.0)),
                ('commission_receivable', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lider.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.report')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
    ]
