# Generated by Django 3.2.8 on 2022-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'grupo supervisor',
                'verbose_name_plural': 'grupos supervisores',
            },
        ),
    ]
