# Generated by Django 3.2.8 on 2022-04-15 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisores', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo supervisor',
                'verbose_name_plural': 'grupos supervisores',
            },
        ),
    ]
